### ISSUE TITLE
Justify Fields

### ISSUE THREAD

**Issue by BrewertonSantos** [lucasgdb/my-finances-app#1]
I'm `settings` window, I think the fields can be justified to improve the visualization.
the fields that we know may contain larger text can be placed below the title.
Is only a suggest

![Settings](https://user-images.githubusercontent.com/55927647/78561141-9b9e0380-77ed-11ea-9172-3ef67d5a0f04.jpg)

**Comment by lucasgdb** [comment]
Thanks for the issue @BrewertonSantos :)
